/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Administrador
 */
public class JuegoLetrasView extends javax.swing.JFrame {

    /**
     * Creates new form JuegoLetrasView
     */
    public JuegoLetrasView() {
        initComponents();
    }

    public String getTextoIntroducido() {
        return inputTextField.getText().trim().replaceAll("\\s+", " ");
    }

    public void actualizarContadores(int vocales, int letras,
            int mayusculas, int palabras) {
        contadorVocalesLabel.setText(String.valueOf(vocales));
        contadorLetrasLabel.setText(String.valueOf(letras));
        contadorMayusLabel.setText(String.valueOf(mayusculas));
        contadorPalabrasLabel.setText(String.valueOf(palabras));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fraseLabel = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        vocalesLabel = new javax.swing.JLabel();
        letrasLabel = new javax.swing.JLabel();
        mayusculasLabel = new javax.swing.JLabel();
        palabrasLabel = new javax.swing.JLabel();
        contadorVocalesLabel = new javax.swing.JLabel();
        contadorLetrasLabel = new javax.swing.JLabel();
        contadorMayusLabel = new javax.swing.JLabel();
        contadorPalabrasLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fraseLabel.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        fraseLabel.setText("Frase");

        inputTextField.setMaximumSize(new java.awt.Dimension(400, 400));
        inputTextField.setMinimumSize(new java.awt.Dimension(400, 400));

        vocalesLabel.setText("Vocales");

        letrasLabel.setText("Letras");

        mayusculasLabel.setText("Mayusculas");

        palabrasLabel.setText("Palabras");

        contadorVocalesLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        contadorVocalesLabel.setForeground(new java.awt.Color(255, 0, 0));
        contadorVocalesLabel.setText("0");
        contadorVocalesLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        contadorVocalesLabel.setMinimumSize(new java.awt.Dimension(15, 15));

        contadorLetrasLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        contadorLetrasLabel.setForeground(new java.awt.Color(255, 0, 0));
        contadorLetrasLabel.setText("0");
        contadorLetrasLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        contadorLetrasLabel.setMinimumSize(new java.awt.Dimension(15, 15));

        contadorMayusLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        contadorMayusLabel.setForeground(new java.awt.Color(255, 0, 51));
        contadorMayusLabel.setText("0");
        contadorMayusLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        contadorMayusLabel.setMinimumSize(new java.awt.Dimension(15, 15));

        contadorPalabrasLabel.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        contadorPalabrasLabel.setForeground(new java.awt.Color(255, 51, 51));
        contadorPalabrasLabel.setText("0");
        contadorPalabrasLabel.setMaximumSize(new java.awt.Dimension(15, 15));
        contadorPalabrasLabel.setMinimumSize(new java.awt.Dimension(15, 15));
        contadorPalabrasLabel.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fraseLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vocalesLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(contadorVocalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letrasLabel)
                                    .addComponent(contadorLetrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mayusculasLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(contadorMayusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(palabrasLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(contadorPalabrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fraseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vocalesLabel)
                    .addComponent(letrasLabel)
                    .addComponent(mayusculasLabel)
                    .addComponent(palabrasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contadorVocalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contadorLetrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contadorMayusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contadorPalabrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoLetrasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoLetrasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoLetrasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoLetrasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoLetrasView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorLetrasLabel;
    private javax.swing.JLabel contadorMayusLabel;
    private javax.swing.JLabel contadorPalabrasLabel;
    private javax.swing.JLabel contadorVocalesLabel;
    private javax.swing.JLabel fraseLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel letrasLabel;
    private javax.swing.JLabel mayusculasLabel;
    private javax.swing.JLabel palabrasLabel;
    private javax.swing.JLabel vocalesLabel;
    // End of variables declaration//GEN-END:variables
}
